<?php echo $this->doctype() ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Zend Framework Quickstart Application</title>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl(). '/css/bootstrap.css') ?>
</head>
<body>
<div id="header" style="background-color: #b5d2ee; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
    </div>
</div>
<div id="header-navigation" class="nav navbar-nav">
    <?php echo
    $this->navigation()->menu()->renderMenu($this->miscnavigation, array('ulClass' => 'nav navbar-nav'));
    ?>
</div>
<div class="container">
    <?php echo $this->layout()->content ?>
</div>
</body>
</html>