<?php
echo $this->headScript()->appendFile($this->baseUrl().'/js/frontend.js', 'text/javascript');
?>
<ul id="test">
    <?php
    /**
     * @var Product $product
     */
    /*
    foreach ($this->products as $product) {
        echo '<li>'. $product->getName() .'</li>';
    }*/
    foreach ($this->paginator as $product) {
        echo '<li>' . $product['Name'] . '</li>';
    }

    ?>
</ul>

<?php

echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
?>

<div>asdasdasdasdasdasdasdasdadsasdasdasda sdas das da sdas das dasd</div>
