<?php
// This file generated by Propel 1.7.1 convert-conf target
return array (
  'BaseProduct' => 'strona/om/BaseProduct.php',
  'BaseProductPeer' => 'strona/om/BaseProductPeer.php',
  'BaseProductQuery' => 'strona/om/BaseProductQuery.php',
  'BaseUsers' => 'strona/om/BaseUsers.php',
  'BaseUsersPeer' => 'strona/om/BaseUsersPeer.php',
  'BaseUsersQuery' => 'strona/om/BaseUsersQuery.php',
  'Product' => 'strona/Product.php',
  'ProductPeer' => 'strona/ProductPeer.php',
  'ProductQuery' => 'strona/ProductQuery.php',
  'ProductTableMap' => 'strona/map/ProductTableMap.php',
  'Users' => 'strona/Users.php',
  'UsersPeer' => 'strona/UsersPeer.php',
  'UsersQuery' => 'strona/UsersQuery.php',
  'UsersTableMap' => 'strona/map/UsersTableMap.php',
);